# Site Settings
title: "ATIAM Master Project"
title_separator: "-"
subtitle: "2025-2026"
name: "ATIAM students"
description: "MSS project using CLASS and FastMNMF"
url: "https://loguerci.github.io"
baseurl: "/CLASS_website"
repository: "loguerci/CLASS_website"

# Navigation
main:
  - title: "Home"
    url: /
  - title: "Photos"
    url: /photo
  - title: "Audio files"
    url: /audio
  - title: "Paper"
    url: /assets/test.pdf

# Theme
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"

# Site Author
author:
  name: "LASS PAM Team"
  avatar: # "/assets/images/bio-photo.jpg"
  bio: "ATIAM students - IRCAM, Paris"
  location: "Paris, France"
  email: "guerci@ircam.fr"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/loguerci/LASS_PAM"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/loguerci/LASS_PAM"

# Reading Files
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true